# Generated by Django 4.2.10 on 2024-02-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrecords',
            old_name='transactionID',
            new_name='transactionid',
        ),
    ]
