# Generated by Django 4.2.10 on 2024-02-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_paymentrecords_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecords',
            name='transactionid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
