# Generated by Django 4.2.10 on 2024-02-09 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_mumbaicounselling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aniket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')])),
                ('telegram', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')])),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=40, null=True)),
                ('pcmscore', models.PositiveIntegerField(blank=True, null=True)),
                ('pcbscore', models.PositiveIntegerField(blank=True, null=True)),
                ('centralscore', models.PositiveIntegerField(blank=True, null=True)),
                ('preference', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('pharmacy', 'Pharmacy'), ('both', 'Both')], max_length=40, null=True)),
                ('locations', models.CharField(blank=True, choices=[('ahmednagar', 'Ahmednagar'), ('akola', 'Akola')], max_length=40, null=True)),
                ('source', models.CharField(blank=True, choices=[('Option1', 'Team Learnolet YouTube Channel (Aniket Mane)'), ('Option2', 'Concept Simplified YouTube Channel (Samkit Shah)'), ('Option3', 'Other (Friends, Social media, Swift Undergrads telegram channel, etc)')], default='Option1', max_length=40, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Samkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')])),
                ('telegram', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')])),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=40, null=True)),
                ('pcmscore', models.PositiveIntegerField(blank=True, null=True)),
                ('pcbscore', models.PositiveIntegerField(blank=True, null=True)),
                ('centralscore', models.PositiveIntegerField(blank=True, null=True)),
                ('preference', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('pharmacy', 'Pharmacy'), ('both', 'Both')], max_length=40, null=True)),
                ('locations', models.CharField(blank=True, choices=[('ahmednagar', 'Ahmednagar'), ('akola', 'Akola')], max_length=40, null=True)),
                ('source', models.CharField(blank=True, choices=[('Option1', 'Team Learnolet YouTube Channel (Aniket Mane)'), ('Option2', 'Concept Simplified YouTube Channel (Samkit Shah)'), ('Option3', 'Other (Friends, Social media, Swift Undergrads telegram channel, etc)')], default='Option2', max_length=40, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='MaharashtraCounselling',
        ),
    ]
