# Generated by Django 4.2.10 on 2024-02-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_others_alter_aniket_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniket',
            name='locations',
            field=models.CharField(blank=True, choices=[('ahmednagar', 'Ahmednagar'), ('akola', 'Akola'), ('amravati', 'Amravati'), ('beed', 'Beed'), ('bhandara', 'Bhandara'), ('buldhana', 'buldhana'), ('chandrapur', 'Chandrapur'), ('aurangabad', 'Chhatrapati Sambhaji Nagar'), ('dharashiv', 'Dharashiv'), ('dhule', 'Dhule'), ('gadchiroli', 'Gadchiroli'), ('gondia', 'Gondia'), ('hingoli', 'Hingoli'), ('jalgaon', 'Jalgaon'), ('kolhpaur', 'Kolhpaur'), ('latur', 'Latur'), ('mumbai', 'Mumbai'), ('nagpur', 'Nagpur'), ('nanded', 'Nanded'), ('nandurbar', 'Nandurbar'), ('nashik', 'Nashik'), ('palghar', 'Palghar'), ('parbhani', 'Parbhani'), ('pune', 'Pune'), ('raigad', 'Raigad'), ('ratnagiri', 'Ratnagiri'), ('sangli', 'Sangli'), ('satara', 'Satara'), ('solapur', 'Solapur'), ('sindhudurg', 'Sindhudurg'), ('thane', 'Thane'), ('wardha', 'Wardha'), ('washim', 'Washim'), ('yavatmal', 'Yavatmal'), ('outside', 'Outside Maharshtra')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='locations',
            field=models.CharField(blank=True, choices=[('ahmednagar', 'Ahmednagar'), ('akola', 'Akola'), ('amravati', 'Amravati'), ('beed', 'Beed'), ('bhandara', 'Bhandara'), ('buldhana', 'buldhana'), ('chandrapur', 'Chandrapur'), ('aurangabad', 'Chhatrapati Sambhaji Nagar'), ('dharashiv', 'Dharashiv'), ('dhule', 'Dhule'), ('gadchiroli', 'Gadchiroli'), ('gondia', 'Gondia'), ('hingoli', 'Hingoli'), ('jalgaon', 'Jalgaon'), ('kolhpaur', 'Kolhpaur'), ('latur', 'Latur'), ('mumbai', 'Mumbai'), ('nagpur', 'Nagpur'), ('nanded', 'Nanded'), ('nandurbar', 'Nandurbar'), ('nashik', 'Nashik'), ('palghar', 'Palghar'), ('parbhani', 'Parbhani'), ('pune', 'Pune'), ('raigad', 'Raigad'), ('ratnagiri', 'Ratnagiri'), ('sangli', 'Sangli'), ('satara', 'Satara'), ('solapur', 'Solapur'), ('sindhudurg', 'Sindhudurg'), ('thane', 'Thane'), ('wardha', 'Wardha'), ('washim', 'Washim'), ('yavatmal', 'Yavatmal'), ('outside', 'Outside Maharshtra')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='samkit',
            name='locations',
            field=models.CharField(blank=True, choices=[('ahmednagar', 'Ahmednagar'), ('akola', 'Akola'), ('amravati', 'Amravati'), ('beed', 'Beed'), ('bhandara', 'Bhandara'), ('buldhana', 'buldhana'), ('chandrapur', 'Chandrapur'), ('aurangabad', 'Chhatrapati Sambhaji Nagar'), ('dharashiv', 'Dharashiv'), ('dhule', 'Dhule'), ('gadchiroli', 'Gadchiroli'), ('gondia', 'Gondia'), ('hingoli', 'Hingoli'), ('jalgaon', 'Jalgaon'), ('kolhpaur', 'Kolhpaur'), ('latur', 'Latur'), ('mumbai', 'Mumbai'), ('nagpur', 'Nagpur'), ('nanded', 'Nanded'), ('nandurbar', 'Nandurbar'), ('nashik', 'Nashik'), ('palghar', 'Palghar'), ('parbhani', 'Parbhani'), ('pune', 'Pune'), ('raigad', 'Raigad'), ('ratnagiri', 'Ratnagiri'), ('sangli', 'Sangli'), ('satara', 'Satara'), ('solapur', 'Solapur'), ('sindhudurg', 'Sindhudurg'), ('thane', 'Thane'), ('wardha', 'Wardha'), ('washim', 'Washim'), ('yavatmal', 'Yavatmal'), ('outside', 'Outside Maharshtra')], max_length=40, null=True),
        ),
    ]
