# Generated by Django 4.2.10 on 2024-03-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_aniket_locations_alter_others_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniket',
            name='source',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='source',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='samkit',
            name='source',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
