# Generated by Django 4.2.10 on 2024-03-10 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_aniket_source_alter_others_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')])),
                ('telegram', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')])),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=40, null=True)),
                ('pcmscore', models.PositiveIntegerField(blank=True, null=True)),
                ('pcbscore', models.PositiveIntegerField(blank=True, null=True)),
                ('centralscore', models.PositiveIntegerField(blank=True, null=True)),
                ('preference', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('pharmacy', 'Pharmacy'), ('both', 'Both')], max_length=40, null=True)),
                ('locations', models.CharField(blank=True, choices=[('ahmednagar', 'Ahmednagar'), ('akola', 'Akola'), ('amravati', 'Amravati'), ('beed', 'Beed'), ('bhandara', 'Bhandara'), ('buldhana', 'buldhana'), ('chandrapur', 'Chandrapur'), ('aurangabad', 'Chhatrapati Sambhaji Nagar'), ('dharashiv', 'Dharashiv'), ('dhule', 'Dhule'), ('gadchiroli', 'Gadchiroli'), ('gondia', 'Gondia'), ('hingoli', 'Hingoli'), ('jalgaon', 'Jalgaon'), ('kolhpaur', 'Kolhpaur'), ('latur', 'Latur'), ('mumbai', 'Mumbai'), ('nagpur', 'Nagpur'), ('nanded', 'Nanded'), ('nandurbar', 'Nandurbar'), ('nashik', 'Nashik'), ('palghar', 'Palghar'), ('parbhani', 'Parbhani'), ('pune', 'Pune'), ('raigad', 'Raigad'), ('ratnagiri', 'Ratnagiri'), ('sangli', 'Sangli'), ('satara', 'Satara'), ('solapur', 'Solapur'), ('sindhudurg', 'Sindhudurg'), ('thane', 'Thane'), ('wardha', 'Wardha'), ('washim', 'Washim'), ('yavatmal', 'Yavatmal'), ('outside', 'Outside Maharshtra')], max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Swift',
                'verbose_name_plural': 'Maharashtra: Swift Undergrads',
            },
        ),
    ]
