# Generated by Django 4.2.8 on 2024-03-29 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_swift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniket',
            name='centralscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aniket',
            name='pcbscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aniket',
            name='pcmscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aniket',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
        migrations.AlterField(
            model_name='aniket',
            name='telegram',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactno',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
        migrations.AlterField(
            model_name='mumbaicounselling',
            name='studentPhone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
        migrations.AlterField(
            model_name='mumbaicounselling',
            name='studentTelegram',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
        migrations.AlterField(
            model_name='mumbaicounselling',
            name='studentjeescore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaicounselling',
            name='studentpcmscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='centralscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='pcbscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='pcmscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
        migrations.AlterField(
            model_name='others',
            name='telegram',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
        migrations.AlterField(
            model_name='samkit',
            name='centralscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samkit',
            name='pcbscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samkit',
            name='pcmscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samkit',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
        migrations.AlterField(
            model_name='samkit',
            name='telegram',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
        migrations.AlterField(
            model_name='swift',
            name='centralscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swift',
            name='pcbscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swift',
            name='pcmscore',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swift',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
        migrations.AlterField(
            model_name='swift',
            name='telegram',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6000000000, message='Invalid contact number'), django.core.validators.MaxValueValidator(9999999999, message='Invalid contact number')]),
        ),
    ]
